### ISSUE TITLE
Backstop Queue Withdrawal Total Not Matching Set Amount

### ISSUE THREAD

**Issue by rawritude** [blend-capital/blend-ui#139]
When inputting a 1000 LP to withdraw, the queued total is 1040.
As discussed with mootz:

> the total amount queued is correct, being 1.04k BLND-USDC LP.
> 
> The number your inputting is actually the number of SHARES to withdraw.
> 
> Since interest auctions have picked back up again, it looks like shares have accrued by 4% (so shares * 1.04 = LP tokens)
![image](https://github.com/user-attachments/assets/63c7523f-68e9-41f0-80f8-6962c367045e)

**Comment by drew-boy** [comment]
closed with https://github.com/blend-capital/blend-ui/pull/143
