### ISSUE TITLE
Bug: Market assets change on hover but are not clickable

### ISSUE THREAD

**Issue by mootz12** [blend-capital/blend-ui#70]
The assets listed in the Markets > Pool > Details expansion change on hover like they are clickable.

TODO
1. Decide if these should be clickable
2. If yes, route to dashboard, if no, remove hover effect

![image](https://github.com/blend-capital/blend-ui/assets/38118608/f21c1ae0-c215-4565-b683-4cda7f59c5aa)

**Comment by carlosdimatteo** [comment]
I'd say: 
if the whole element is clickable route to a page in the app 
we could also only make the name clickable and link to token/contract page

**Comment by markuspluna** [comment]
The problem with linking to the asset page is we can't determine whether the user wants to lend or borrow - and there are separate asset pages for each. I thinking linking to the dashboard is safest
